version: '2'
services:
  email:
    image: theypsilon/docker-fakesmtp
    container_name: email
  db:
    image: ems-postgresql
    container_name: ems-postgres
    ports:
      - "5442:5432"
  ems-app:
    image: ems
    container_name: ems
    depends_on:
      - db
    ports:
      - "8091:8091"
      - "5015:5005"
  submitit-app:
    image: submitit
    container_name: submitit
    ports: 
      - "8090:8090"
    depends_on:
      - ems-app
      - email
  cake-app:
    image: cake
    container_name: cake
    ports:
      - "8092:8092"
      - "5006:5006"
    depends_on:
      - ems-app
      - email
  api-app:
    image: api
    container_name: api
    ports:
      - "8083:8083"
      - "5007:5007"
    depends_on:
      - ems-app
